# on: push

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 */7 * *"

jobs:
  linux-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Upgrade buildah and install fuse-overlayfs
        run: |
          sudo apt-get -y update
          sudo apt-get install -f buildah podman fuse-overlayfs

      - name: Run build script in buildah unshare session
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          buildah unshare ./build.sh
